import { Container, Row, Col, Button, Form } from 'react-bootstrap'
import { useState } from 'react'
import CalculadoraService from './__test__/calc.service';

export default function Calculadora() {

  const [calcular, concatenarNumero, SOMA, SUBTRACAO, DIVISAO, MULTIPLICACAO] = CalculadoraService();

  const [txtNumeros, setTxtNumeros] = useState('0');
  const [numero1, setNumero1] = useState('0');
  const [numero2, setNumero2] = useState(null);
  const [operacao, setOperacao] = useState(null);

  function addNum(numero: string){
    let resultado;
    if (operacao === null) {
      resultado = concatenarNumero(numero1, numero);
      setNumero1(resultado);
    } else {
      resultado = concatenarNumero(numero2, numero);
      setNumero2(resultado);
    }
    setTxtNumeros(resultado);
  }

  function defOperac(op:string) {
    // apenas define a operação caso ela não exista
    if (operacao === null) {
      setOperacao(op);
      return;
    }
    // caso operação estiver definida e número 2 selecionado, realiza o cálculo da operação
    if (numero2 !== null) {
      const resultado = calcular(parseFloat(numero1), parseFloat(numero2), operacao);
      setOperacao(op);
      setNumero1(resultado.toString());
      setNumero2(null);
      setTxtNumeros(resultado.toString());
    }
  }

  function acaoCalcular() {
    if (numero2 === null) {
      return;
    }
    const resultado = calcular(parseFloat(numero1), parseFloat(numero2), operacao);
    setTxtNumeros(resultado);
  }

  function limpar() {
    setTxtNumeros('0');
    setNumero1('0');
    setNumero2(null);
    setOperacao(null);
  }


  return (
    <>
      <header>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </header>
      <h1 className="p-10">Calculadora</h1>
      <br/>
      <div style={{
        padding: '20px',
        backgroundColor: '#121212',
        margin: '10px',
        background: 'transparent !important',
        width: '400px',
        borderRadius: '10px'
      }}>

      <Container>
      <Row>
          <Col xs="3">
            <Button className="h-60 w-60 " variant="danger" onClick={limpar}>C</Button>
          </Col>
          <Col xs="9">
            <Form.Control className="h-60 w-100 text-right " type="text" 
            name="txtNumeros" 
            value={txtNumeros}
            readOnly/>
          </Col>
        </Row>
        <Row style={{paddingTop:"10px"}}>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('7')}>7</Button>
          </Col>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('8')}>8</Button>
          </Col>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('9')}>9</Button>
          </Col>
          <Col>
            <Button style={{width:"70px", height:"50px"}} variant="warning"
            onClick={() => defOperac(DIVISAO)}>/</Button>
          </Col>
        </Row>
        <Row style={{paddingTop:"10px"}}>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('4')}>4</Button>
          </Col>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('5')}>5</Button>
          </Col>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('6')}>6</Button>
          </Col>
          <Col>
            <Button style={{width:"70px", height:"50px"}} variant="warning"
            onClick={() => defOperac(MULTIPLICACAO)}>*</Button>
          </Col>
        </Row>
        <Row style={{paddingTop:"10px"}}>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('1')}>1</Button>
          </Col>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('2')}>2</Button>
          </Col>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('3')}>3</Button>
          </Col>
          <Col>
            <Button style={{width:"70px", height:"50px"}} variant="warning"
            onClick={() => defOperac(SUBTRACAO)}>-</Button>
          </Col>
        </Row>
        <Row style={{paddingTop:"10px"}}>
          <Col>
            <Button className="h-60 w-60" variant="light"
            onClick={() => addNum('0')}>0</Button>
          </Col>
          <Col>
            <Button className="h-60 w-0" variant="light" onClick={() => addNum('.')}>.</Button>
          </Col>
          <Col>
            <Button className="h-60 w-60" variant="success" onClick={acaoCalcular}>=</Button>
          </Col>
          <Col>
            <Button style={{width:"70px", height:"50px"}} variant="warning"
            onClick={() => defOperac(SOMA)}>+</Button>
          </Col>
        </Row>
      </Container>
      </div>

    </>
  )
}
